/**
 * Booking service — client-side API calls for reservation creation.
 *
 * Uses clientFetch (which goes through the Next.js API proxy at /api/v1/[...path])
 * so cookies/session are sent automatically without exposing tokens to JS.
 *
 * Backend endpoints used:
 *   POST /api/v1/reservations — create reservation + Stripe PaymentIntent
 *
 * Backend response for POST /reservations:
 *   { data: Reservation } where Reservation includes:
 *     id (UUID), status, pickupDate, returnDate, totalDays,
 *     totalPriceEurCents, depositEurCents, pickupLocation,
 *     stripeClientSecret (nullable), stripePaymentIntentId (nullable),
 *     qrCodeHash (nullable), customerName, customerPhone,
 *     vehicle (eager-loaded), userId, createdAt, updatedAt
 */

import { clientFetch } from "@/lib/api/client-fetch";
import { normalizeApiError, type ApiErrorPayload } from "@/lib/api/errors";
import type {
  ReservationCreateDto,
  QuoteReservationDto,
  QuoteViewModel,
  VehicleAvailabilityCalendar,
} from "./types";

// ---------------------------------------------------------------------------
// Response types
// ---------------------------------------------------------------------------

/**
 * Raw backend reservation object returned from POST /reservations.
 * Dates come as ISO strings (JSON serialization of Date entities).
 * This type reflects what the backend actually sends — do not add computed fields.
 */
export type ReservationApiResponse = {
  id: string;
  status: string;
  pickupDate: string;
  returnDate: string;
  totalDays: number;
  totalPriceEurCents: number;
  depositEurCents: number;
  dailyRateEurCentsSnapshot?: number;
  subtotalEurCents?: number;
  totalDueNowEurCents?: number;
  chargedDayUnitsX2?: number;
  fullDays?: number;
  extraHours?: number;
  extraBillingType?: string;
  pricingPolicyVersion?: string;
  currency?: string;
  pickupLocation: string;
  stripeClientSecret: string | null;
  stripePaymentIntentId: string | null;
  qrCodeHash: string | null;
  customerName: string | null;
  customerPhone: string | null;
  userId: string;
  createdAt: string;
  updatedAt: string;
  vehicle?: {
    id: string;
    brand?: string;
    model?: string;
    imageUrl?: string;
    pricePerDayEurCents?: number;
    category?: string;
  };
};

type CreateReservationResponse = {
  data: ReservationApiResponse;
};

// ---------------------------------------------------------------------------
// Result type — either success or normalized error
// ---------------------------------------------------------------------------

export type CreateReservationResult =
  | { ok: true; reservation: ReservationApiResponse }
  | { ok: false; error: ApiErrorPayload };

// ---------------------------------------------------------------------------
// createReservation
// ---------------------------------------------------------------------------

/**
 * Calls POST /api/v1/reservations with an idempotency key.
 *
 * Idempotency semantics:
 * - The key must be generated by the caller BEFORE calling this function.
 * - On network error or retry, pass the same key — backend will deduplicate.
 * - On success, caller must clear the key via clearIdempotencyKey().
 * - On 409 (conflict): do NOT generate a new key. Show a clear message.
 * - On 400/422 (validation): do NOT clear the key. User can fix and retry.
 *
 * The stripeClientSecret in the response is transient:
 * - Do not store in localStorage.
 * - Do not log.
 * - Pass directly to the Stripe payment element (Commit I).
 */
export async function createReservation(
  dto: ReservationCreateDto,
  idempotencyKey: string,
): Promise<CreateReservationResult> {
  try {
    const response = await clientFetch<CreateReservationResponse>(
      "/reservations",
      {
        method: "POST",
        body: dto as unknown as Record<string, unknown>,
        headers: {
          "Idempotency-Key": idempotencyKey,
        },
      },
    );

    return { ok: true, reservation: response.data };
  } catch (error) {
    return { ok: false, error: normalizeApiError(error) };
  }
}

// ---------------------------------------------------------------------------
// quoteReservation
// ---------------------------------------------------------------------------

export type QuoteReservationResult =
  | { ok: true; quote: QuoteViewModel }
  | { ok: false; error: ApiErrorPayload };

export async function quoteReservation(
  dto: QuoteReservationDto,
  signal?: AbortSignal,
): Promise<QuoteReservationResult> {
  try {
    const response = await clientFetch<{ data: QuoteViewModel }>(
      "/reservations/quote",
      {
        method: "POST",
        body: dto as unknown as Record<string, unknown>,
        signal,
      },
    );

    return { ok: true, quote: response.data };
  } catch (error) {
    return { ok: false, error: normalizeApiError(error) };
  }
}

export async function getVehicleAvailabilityCalendar(
  vehicleId: string,
  from: string,
  to: string,
  signal?: AbortSignal,
): Promise<VehicleAvailabilityCalendar> {
  const params = new URLSearchParams({ from, to });
  const response = await clientFetch<{ data: VehicleAvailabilityCalendar }>(
    `/vehicles/${encodeURIComponent(vehicleId)}/availability-calendar?${params.toString()}`,
    { signal },
  );

  return response.data;
}
